export const colors = {
    neutral: '#EFEFEF',
    white: '#FFFFFF',
    redAccent: '#FF383F',
    carbon: '#454545',
    black: '#000000',
    ink: '#062F4F',
    buttonText: '#454545',
    sky: '#CAEBF2',
    navy: '#18121E',
    translucent: 'rgba(255, 255, 255, 0.7)',
};
export const style = {
    textInputHeight: 40,
    textInputHeightLarge: 80,
    inputWidthDifference: 60,
    inputBorderRadius: 5,
    inputFontSize: 16,
    largeFontSize: 25,
    titleFontSize: 20,
    inputMarginHorizontal: 10,
    inputPaddingVertical: 5,
    inputPaddingHorizontal: 15,
    titleMargin: 5,
    containerWidthDifference: 50,
    containerMarginHorizontal: 5,
    borderRadius: 10,
    margin: 10,
    padding: 20,
    listRowPadding: 10,
    buttonPadding: 20,
    homeButtonSize: 125,
    iconButtonSize: 60,
    iconButtonFontSize: 14,
    modalWidthDifference: 20,
    listRowIconSize: 60,
    headerImageSize: 50,
    submitButtonHeight: 50,
    submitButtonWidth: 250,
};